<!DOCTYPE html>
<html lang="ru">
    <?php include_once 'partials/head.phtml'; ?>
    <body>
        <div class="container">
        <nav>

        </nav>
        <main>
            <header><?=$header ?></header>
            <section>
                <p><?=$message ?></p>
            </section>
        </main>
        </div>
    </body>
</html>
<?php include_once 'partials/footer.phtml'; ?>