<!DOCTYPE html>
<html lang="ru">
    <?php include_once 'partials/head.phtml'; ?>
    <body>
        <div class="container">
        <nav>

        </nav>
        <main>
            <header><h1>Расписание</h1></header>
            <table class="main-list">
                <tr>

                </tr>
            </table>
        </main>
        </div>
    </body>
    <?php include_once 'partials/footer.phtml'; ?>
</html>